### ISSUE TITLE
Nothing shows up

### ISSUE THREAD

**Issue by Raphull** [AstraaDev/Discord-Token-Grabber#34]
As soon as i press enter in cmd everything works fine but the Discord Integration just doesn't send a message

**Comment by Nayza-bytes** [comment]
Hello, I have the same problem as you, and I'm trying to find a solution online.
Nothing is sent because of the error "HHTP error 400: Bad request".
Here is the part of the code where you modify the webhook URL, and I modified the except part to print the error !
I'm coming back when i got something working !!

![image](https://user-images.githubusercontent.com/85430899/184383369-74194f93-d58e-47e7-ab76-3e66c4ac6d20.png)

**Comment by Raphull** [comment]
Hi, thanks very much for working on it! I don't know python very well myself but im trying to learn it :D

**Comment by Nayza-bytes** [comment]
Hello again, this is cool that you are learning Python because it's a great language !! 

I have found something, but another error came XD, anyway I found a python library that you need to install called dhooks (On the screen) that you can install with the command `pip install dhooks` in your terminal.

On the other screen you can see what I modified and the new error that pops up is `One of content, embed/embeds, or file must be set`. I'm still working on it and when it's done I will give you the modified version of the token grab.
![image](https://user-images.githubusercontent.com/85430899/184386441-a4be43bf-70d5-47a7-abaf-1013550e42a0.png)


![image](https://user-images.githubusercontent.com/85430899/184386196-6567440b-69d2-46b4-997a-23c65bc8935f.png)

**Comment by Nayza-bytes** [comment]
Hello again,
I'm blind because I didn't see there was a link to the fixed token grabber on the README, so I stopped the work
![image](https://user-images.githubusercontent.com/85430899/184390854-6a2b051a-6ec8-4525-8352-6bebef836d57.png)

**Comment by riso38** [comment]
write on instagram seve.services for working grabber

**Comment by Gracehearts** [comment]
hey i havent got back into my account where did u write cmd
